###
GET http://localhost:3003/api/blogs/
###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InB1cGtpbmUtMkBleGFtcGxlLmNvbSIsImlkIjoiNWY4NGI3Y2M4ZDRkMjI1Y2M0YzFlMzE2IiwiaWF0IjoxNjAyNTM4OTY5fQ.YVSwzwqDzw_kyOQjR3dTSXNiWGOr8M6I4WVvU15LahY

{
  "title": "Bool-bool Tok-Tok",
  "author": "_YA",
  "url": "http://google.com",
  "likes": 323232
}

###
POST http://localhost:3003/api/login/
content-type: application/json

{
  "login": "pupkine-2@example.com",
  "password": "123pupkine2"
}