###
GET http://localhost:3003/api/blogs/
###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "title": "Bool-bool333",
  "author": "_YA",
  "url": "http://google.com",
  "likes": 32
}

###
POST http://localhost:3003/api/login/
content-type: application/json

{
  "login": "pupkine-2@example.com",
  "password": "123pupkine2"
}